### ISSUE TITLE
Update harvard contact page.

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-ui#1040]
Replace existing text on contact page with Harvard Specific ones. Please use formatting similar to that of the JHU contact page. 

> For help with using PASS or questions about policies & compliance, copyrights or other topics relating to scholarly output, please contact:   
**Office for Scholarly Communication**
Harvard Library | Harvard University | Cambridge, MA 02138 
OSC@harvard.edu 

> For help with issues relating to grants and publication submissions data, please contact:
> **Scott Lapinski**
> Associate Director, Scholarly Communication and Open Science Initiatives 
> Countway Library | Harvard University | Boston, MA 02115
> p_lapinski@ms.harvard.edu

**Comment by jabrah** [comment]
Do we prefer the vertical or horizontal arrangement for this contact page?

![Screenshot from 2019-08-30 10-56-01](https://user-images.githubusercontent.com/5167587/64030535-c7992e00-cb14-11e9-8c48-4ecb56584f3b.png)

![Screenshot from 2019-08-30 10-54-01](https://user-images.githubusercontent.com/5167587/64030399-7f7a0b80-cb14-11e9-8021-a05c95dd01b4.png)

**Comment by htpvu** [comment]
@jabrah i didn't see this comment. I prefer horizontal placement. Which on made it to the image?

**Comment by jabrah** [comment]
pretty sure the horizontal arrangement made it to the image
