### ISSUE TITLE
Update harvard FAQ page

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-ui#1041]
Remove all FAQs except for these:

- What Open or Public Access policies can PASS support?
- Will the publisher automatically submit my article to PubMed Central?
- What information about NIH submissions is pre-loaded into PASS?
-- **NOTE**: in this question, please update the "**contact us**" link to point to the correct contact page. maybe use relative url here 

Add this content to the page:

> For FAQs specific to Harvard affiliated users, see http://bit.ly/Harvard-PASS-FAQ

**Comment by jabrah** [comment]
So I should simply have a link to the Harvard PASS-FAQ on the page

**Comment by htpvu** [comment]
Please add the following changes to the FAQ page.

<img width="1335" alt="Screen Shot 2019-09-03 at 9 22 28 PM" src="https://user-images.githubusercontent.com/11050142/64223958-bef18080-cea3-11e9-9b07-3ff8fe19bde7.png">

**Comment by htpvu** [comment]
@jabrah can this be closed?
